module.exports = {
    0: "CooldownNone",             // "Temporary Matchmaking Cooldown (No reason)"
    1: "Kicked",                   // "You have been kicked from your last matchmaking game."
    2: "KilledMate",               // "You killed too many teammates."
    3: "RoundStartKill",           // "You killed a teammate at round start."
    4: "FailReconnect",            // "You failed to reconnect to your last match."
    5: "Abandon",                  // "You abandoned your last match."
    6: "DamagedMate",              // "You dealt too much damage to your teammates."
    7: "DamagedMateStart",         // "You dealt too much damage to your teammates at round start."
    8: "UntrustedAngles",          // "Your account is permanently untrusted. (Illegal Angles)"
    9: "KickedTooMuch",            // "You were kicked from too many recent matches."
    10: "MajorlyDisruptive",       // "Convicted by Overwatch: Majorly Disruptive"
    11: "MinorlyDisruptive",       // "Convicted by Overwatch: Minorly Disruptive"
    12: "ResolveState",            // "Resolving Matchmaking state for your account."
    13: "ResolveStateLastMatch",   // "Resolving Matchmaking state for your last match."
    14: "UntrustedVac",            // "Your account is permanently untrusted. (VAC)"
    15: "PermanentCooldownNone",   // "Permanent Matchmaking Cooldown (No reason)"
    16: "FailConnect",             // "You failed to connect by match start."
    17: "KickedMates",             // "You kicked too many teammates in recent matches."
    18: "NewbieCooldown",          // "Your account is under skill placement calibration."
    19: "GameServerBanned",        // "A server using your game server token has been banned."
};
